# Generated by Django 4.0.5 on 2022-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
