# Generated by Django 4.0.5 on 2022-06-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0004_alter_user_dob_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
